d:
	cmake --build build/debug --target 2DCellularLightingRaylib
	./build/debug/2DCellularLightingRaylib.exe

b:
	cmake -Bbuild/debug -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .

c:
	cp build/debug/compile_commands.json .
